#include "Camera.h"
#include "glm/gtc/type_ptr.inl"
#include "IndexBuffer.h"
#include "Renderer.h"
#include "Shader.h"
#include "VertexArray.h"
#include <glm/gtx/vector_angle.hpp>
#include <limits>
#include <Texture.h>

static std::string DebugConvertSeverityToString(GLenum severity)
{
	switch (severity)
	{
	case GL_DEBUG_SEVERITY_LOW:
		return "GL_DEBUG_SEVERITY_LOW:Redundant state change performance warning, or unimportant undefined behavior";
	case GL_DEBUG_SEVERITY_MEDIUM:
		return
			"GL_DEBUG_SEVERITY_MEDIUM:Major performance warnings, shader compilation/linking warnings, or the use of deprecated functionality";
	case GL_DEBUG_SEVERITY_HIGH:
		return
			"GL_DEBUG_SEVERITY_HIGH:All OpenGL Errors, shader compilation/linking errors, or highly-dangerous undefined behavior";
	case GL_DEBUG_SEVERITY_NOTIFICATION:
		return "GL_DEBUG_SEVERITY_NOTIFICATION:Anything that isn't an error or performance issue.";
	}
}

static std::string DebugConvertSourceToString(GLenum Source)
{
	switch (Source)
	{
	case GL_DEBUG_SOURCE_API:
		return "GL_DEBUG_SOURCE_API: Calls to the OpenGL API";
	case GL_DEBUG_SOURCE_WINDOW_SYSTEM:
		return "GL_DEBUG_SOURCE_WINDOW_SYSTEM: Calls to a window-system API";
	case GL_DEBUG_SOURCE_SHADER_COMPILER:
		return "GL_DEBUG_SOURCE_SHADER_COMPILER: A compiler for a shading language";
	case GL_DEBUG_SOURCE_THIRD_PARTY:
		return "GL_DEBUG_SOURCE_THIRD_PARTY:An application associated with OpenGL";
	case GL_DEBUG_SOURCE_APPLICATION:
		return "GL_DEBUG_SOURCE_APPLICATION:Generated by the user of this application";
	case GL_DEBUG_SOURCE_OTHER:
		return "GL_DEBUG_SOURCE_OTHER:Some source that isn't one of these";
	}
}

static std::string DebugConvertTypeToString(GLenum type)
{
	switch (type)
	{
	case GL_DEBUG_TYPE_ERROR:
		return "GL_DEBUG_TYPE_ERROR: An error, typically from the API";
	case GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR:
		return "GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR	: Some behavior marked deprecated has been used";
	case GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR:
		return "GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR: Something has invoked undefined behavior";
	case GL_DEBUG_TYPE_PORTABILITY:
		return "GL_DEBUG_TYPE_PORTABILITY:Some functionality the user relies upon is not portable";
	case GL_DEBUG_TYPE_PERFORMANCE:
		return "GL_DEBUG_TYPE_PERFORMANCE:Code has triggered possible performance issues";
	case GL_DEBUG_TYPE_MARKER:
		return "GL_DEBUG_TYPE_MARKER:Command stream annotation";
	case GL_DEBUG_TYPE_POP_GROUP:
		return "GL_DEBUG_TYPE_POP_GROUP:Group popping";
	case GL_DEBUG_TYPE_PUSH_GROUP:
		return "GL_DEBUG_TYPE_PUSH_GROUP:Group pushing";
	default:
		return "GL_DEBUG_TYPE_OTHER: Some type that isn't one of these";
	}
}

void Renderer::Clear()
{
	// Specify the color of the background
		glClearColor(0.07f, 0.13f, 0.17f, 1.0f);
		// Clean the back buffer and depth buffer
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
}



void Renderer::Draw(Shader& shader, Camera& camera, float camera_angle) 
{
    glm::mat4 cam_mat4 = camera.Matrix(camera_angle, 0.1f, 100.f);
	for (auto& m_Object : m_Objects)
	{
		glm::mat4 model = glm::mat4(1.0f);
		model = glm::translate(model, m_Object.location);
		model = glm::rotate(model, glm::radians(m_Object.rotationY), glm::vec3(0.0f, 1.0f, 0.0f));
		model = glm::scale(model, glm::vec3(m_Object.scaleVal));
		glm::mat4 mvp = cam_mat4 * model;

		shader.SetUniformMat4f("u_mvp", mvp);
		switch(m_Object.shape)
		{
			case Shape::Cube:
				DrawCube(shader);
				break;
			case Shape::Pyramid:
				DrawPyramid(shader);
				break;
			case Shape::Sphere:
				DrawSphere();
				break;
			default:
				break;
		}
	}
}

void Renderer::DrawCube(const Shader& shader)
{
	position =
	{ // COORDINATES                 
		
		//CUBE
		 0.5f, 0.5f,  0.5f,		1.f, 0.f, 0.f,	0.0f, 0.0f,
		-0.5f, 0.5f,  0.5f,		0.f, 1.f, 0.f,	5.0f, 0.0f, 
		-0.5f,-0.5f,  0.5f,		0.f, 0.f, 1.f,	0.0f, 0.0f,
		0.5f,  -0.5f,  0.5f,	1.f, 1.f, 1.f,	5.0f, 0.0f,
		// back
		 0.5,  0.5, -0.5,		1.f, 0.f, 0.f,	0.0f, 0.0f,
		-0.5,  0.5, -0.5,		0.f, 1.f, 0.f,	5.0f, 0.0f,
		 -0.5, -0.5, -0.5,		0.f, 0.f, 1.f,	0.0f, 0.0f,
		 0.5, -0.5, -0.5,		1.f, 1.f, 1.f,	5.0f, 0.0f
	};
	indices = {
		//CUBE
		0, 1, 2,
		2, 3, 0,

      // Right
      0, 3, 7,
      7, 4, 0,

      // Bottom
      2, 6, 7,
      7, 3, 2,

      // Left
      1, 5, 6,
      6, 2, 1,

      // Back
      4, 7, 6,
      6, 5, 4,

      // Top
      5, 1, 0,
      0, 4, 5,
	};
	VertexArray va;

	VertexBuffer vb(position.data(), 4 * position.size());

	VertexBufferLayout layout;
	layout.Push<float>(3);
	layout.Push<float>(3);
	layout.Push<float>(2);
	va.AddBuffer(vb, layout);

	IndexBuffer ib(indices.data(), indices.size()); 
	shader.Bind();
	va.Bind();
	ib.Bind();
	glDrawElements(GL_TRIANGLES, ib.GetCount(),GL_UNSIGNED_INT, 0);
}

void Renderer::DrawPyramid(const Shader& shader)
{
	position =
	{ // COORDINATES                 
	
		-0.5f, 0.0f,  0.5f,     0.f, 1.f, 0.f,	0.0f, 0.0f,
		-0.5f, 0.0f, -0.5f,     0.f, 0.f, 1.f,	5.0f, 0.0f,
		 0.5f, 0.0f, -0.5f,     1.f, 0.f, 0.f,	0.0f, 0.0f,
		 0.5f, 0.0f,  0.5f,     0.f, 1.f, 0.f,	5.0f, 0.0f,
		 0.0f, 0.8f,  0.0f,     0.f, 0.f, 1.f,	2.5f, 5.0f
	};
	indices = {
		//PYRAMID
		0, 1, 2,
		0, 2, 3,
		0, 1, 4,
		1, 2, 4,
		2, 3, 4,
		3, 0, 4
	
   };
	VertexArray va;

	VertexBuffer vb(position.data(), 4 * position.size());

	VertexBufferLayout layout;
	layout.Push<float>(3);
	layout.Push<float>(3);
	layout.Push<float>(2);
	

	va.AddBuffer(vb, layout);

	IndexBuffer ib(indices.data(), indices.size()); 
	shader.Bind();
	va.Bind();
	ib.Bind();
	glDrawElements(GL_TRIANGLES, ib.GetCount(),GL_UNSIGNED_INT, 0);
}

void Renderer::DrawSphere()
{

}

int Renderer::AddObject(Shape shape, const glm::vec3& location, float rotationY, float scaleVal)
{
  const int objectId = m_NextObjectId++;
	m_Objects.push_back({objectId, shape, rotationY, scaleVal, location});
	return objectId;
}

std::vector<Info>& Renderer::GetObjects()
{
	return m_Objects;
}

Info* Renderer::GetObjectById(int id)
{
	for (auto& object : m_Objects)
	{
		if (object.id == id)
			return &object;
	}

	return nullptr;
}

void Renderer::AutoRotateObjects(float deltaDegrees)
{
	for (auto& object : m_Objects)
	{
		object.rotationY += deltaDegrees;
		if (object.rotationY >= 360.0f)
			object.rotationY -= 360.0f;
	}
}

int Renderer::PickObject(const glm::vec3& rayOrigin, const glm::vec3& rayDirection) const
{
	float nearestT = std::numeric_limits<float>::max();
	int selectedId = -1;

	for (const auto& object : m_Objects)
	{
		const float radius = 0.9f * object.scaleVal;
		const glm::vec3 oc = rayOrigin - object.location;
		const float b = 2.0f * glm::dot(oc, rayDirection);
		const float c = glm::dot(oc, oc) - (radius * radius);
		const float discriminant = (b * b) - (4.0f * c);

		if (discriminant < 0.0f)
			continue;

		const float sqrtDisc = sqrtf(discriminant);
		const float t0 = (-b - sqrtDisc) * 0.5f;
		const float t1 = (-b + sqrtDisc) * 0.5f;
		const float t = (t0 > 0.0f) ? t0 : t1;

		if (t > 0.0f && t < nearestT)
		{
			nearestT = t;
			selectedId = object.id;
		}
	}

	return selectedId;
}

void APIENTRY openglCallbackFunction(GLenum source,
                                     GLenum type,
                                     GLuint id,
                                     GLenum severity,
                                     GLsizei length,
                                     const GLchar* message,
                                     const void* userParam)
{
  if (severity == GL_DEBUG_SEVERITY_NOTIFICATION)
		return;

	std::cout << "[OpenGL ERROR]\nSource: " << DebugConvertSourceToString(source) << "\nType: " <<
		DebugConvertTypeToString(type) << "\nID: " << id << "\nSeverity: " << DebugConvertSeverityToString(severity) <<
		"\nMessage: " << message << std::endl;
	if(severity == GL_DEBUG_SEVERITY_HIGH)
		Break;
}

void glCheckError()
{
	glEnable(GL_DEBUG_OUTPUT);
	glEnable(GL_DEBUG_OUTPUT_SYNCHRONOUS);
	glDebugMessageCallback(openglCallbackFunction, nullptr);
   glDebugMessageControl(GL_DONT_CARE, GL_DONT_CARE, GL_DEBUG_SEVERITY_NOTIFICATION, 0, nullptr, GL_FALSE);
}
